# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g_comp <- function(x, d) {
    .Call(`_tailplots_g_comp`, x, d)
}

g_scalar <- function(x, d) {
    .Call(`_tailplots_g_scalar`, x, d)
}

var_gamma <- function(x, d, method = "unbiased", R = 1000L) {
    .Call(`_tailplots_var_gamma`, x, d, method, R)
}

ci_gamma <- function(x, d_vec, method = "unbiased", R = 1000L, conf_level = 0.95) {
    .Call(`_tailplots_ci_gamma`, x, d_vec, method, R, conf_level)
}

s_comp <- function(x, u) {
    .Call(`_tailplots_s_comp`, x, u)
}

s_scalar <- function(x, u) {
    .Call(`_tailplots_s_scalar`, x, u)
}

var_lnorm <- function(x, u, method = "unbiased", R = 1000L) {
    .Call(`_tailplots_var_lnorm`, x, u, method, R)
}

ci_lnorm <- function(x, u_vec, method = "unbiased", R = 1000L, conf_level = 0.95) {
    .Call(`_tailplots_ci_lnorm`, x, u_vec, method, R, conf_level)
}

t_rec <- function(x) {
    .Call(`_tailplots_t_rec`, x)
}

t_scalar <- function(x, u) {
    .Call(`_tailplots_t_scalar`, x, u)
}

t_comp <- function(x, u) {
    .Call(`_tailplots_t_comp`, x, u)
}

var_pareto <- function(x, u, method, R = 1000L) {
    .Call(`_tailplots_var_pareto`, x, u, method, R)
}

ci_pareto <- function(x, u_vec, method, R = 1000L, conf_level = 0.95) {
    .Call(`_tailplots_ci_pareto`, x, u_vec, method, R, conf_level)
}

